version: "3.8"
services:
  service:
    container_name: tapki_lapki_backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./data:/back_info

  database:
    container_name: tapki_lapki_database
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - .env
