spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tapki_lapki_database
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: false
  graphql:
    graphiql:
      enabled: true

logging:
  file:
    name: /back_info/tapki_lapki_backend.log

admin:
  username: MikhailOk
  password: 123456
  email: mikhail.okhapkin@yandex.ru
  real_name:
  second_name:

upload:
  path: /storage